import{Injectable} from '@angular/core'

@Injectable({
  providedIn: 'root'
})
export class notifications {
  notis = [
    {id: '1',tag: 'HSA',title: 'Phổ điểm bài thi HSA ổn định qua các đợt tháng 3-4/2023', date: '28/04/2023, 13:25', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/23a1572d-dd76-43d4-8a75-c8b6fc51c607/download', short: 'Phổ điểm thi của 4 đợt đầu tiên theo phân bổ chuẩn, điểm trung bình 75,2/150; trung vị là 75,0/150; độ lệch chuẩn 13,7. Thí sinh đạt điểm cao nhất 129/150, thấp nhất 31/150. So với cùng kỳ năm 2022, điểm trung bình năm 2023 giảm 2,4 điểm. Phổ điểm ổn định theo từng đợt thi, số thí sinh đạt từ 100 điểm trở lên chiếm 4,4%, trên 75 điểm chiếm 50,8%.' },
    {id: '2',tag: 'HSA',title: 'Hoàn thành đợt thi HSA thứ tư năm 2023', date: '23/04/2023, 16:58', img: 'https://cet.vnu.edu.vn/assets/images/TTKT/no-image.png', short: 'Đợt thi Đánh giá năng lực học sinh trung học phổ thông (HSA) lần thứ tư (đợt thi 304) đã được tổ chức tại 10 điểm thi gồm Trung tâm Khảo thí Đại học Quốc gia Hà Nội (ĐHQGHN), Trường Đại học Khoa học Xã hội và Nhân văn - ĐHQGHN, Trường Đại học Kinh tế Quốc dân, Trường Đại học Tài nguyên Môi trường Hà Nội, Trường Đại học Công nghiệp Hà Nội, Trường Đại học Thăng Long, Học viện Ngân hàng, Trung tâm Khảo thí và Quản lý chất lượng - ĐH Thái Nguyên, Trường Đại học Vinh (Nghệ An) và Sở Giáo dục & Đào tạo ' },
    {id: '3',tag: 'dai hoc',title: 'Hội nghị Sơ kết công tác giữa nhiệm kỳ Đại hội nhiệm kỳ 2020-2025 và Lễ kết nạp Đảng viên mới năm 2023', date: '31/03/2023, 17:05', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/80a1abd7-bc4e-448a-89e5-bf004a664f01/download', short: 'Chiều ngày 30/03/2023 tại Tòa HT2, Khu đô thị Đại học Quốc gia Hà Nội (ĐHQGHN) tại Hòa Lạc, Chi bộ Trung tâm Khảo thí ĐHQGHN đã tổ chức Hội nghị Sơ kết công tác giữa nhiệm kỳ Đại hội nhiệm kỳ 2020-202 và Lễ kết nạp Đảng viên mới năm 2023' },
    {id: '4',tag: 'dai hoc',title: 'Trung tâm Khảo thí ĐHQGHN là đơn vị đầu tiên tổ chức Đại hội Đại biểu Công đoàn cấp cơ sở', date: '31/03/2023, 11:01', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/5f80c7c3-0936-4a64-9c78-f92a25d30644/download', short: 'Sáng ngày 30/3/2023, Công đoàn Trung tâm Khảo thí ĐHQGHN hân hoan tổ chức Đại hội Công đoàn Trung tâm Khảo thí ĐHQGHN lần thứ II, nhiệm kỳ 2023-2028. Đây là đơn vị đầu tiên của ĐHQGHN tổ chức Đại hội công đoàn cấp cơ sở.' },
    {id: '5',tag: 'HSA',title: 'Hơn 12.000 thí sinh dự thi HSA đợt hai năm 2023', date: '26/03/2023, 18:02', img: 'https://cet.vnu.edu.vn/assets/images/TTKT/no-image.png', short: 'Trong hai ngày 25-26/03/2023, đợt thi HSA thứ hai (302) của kỳ thi Đánh giá năng lực của ĐHQGHN đã diễn ra tại 8 địa điểm thi gồm Trung tâm Khảo thí ĐHQGHN, Trường Đại học Công nghệ, Trường Đại học Khoa học Xã hội & Nhân văn, Học viện Ngân hàng, Trường Đại học Thăng Long, Trường ĐH Tài nguyên Môi trường, Trường Đại học Công nghiệp Hà Nội, Sở Giáo dục & Đào tạo Hải Phòng. Số lượng đăng ký dự thi đợt hai là 12.266 thí sinh, tỉ lệ thí sinh dự thi đợt 302 đạt 98,1 %.' },
    {id: '6',tag: 'HSA',title: 'Mở cổng đăng ký thi HSA đợt tháng 5-6 năm 2023', date: '18/03/2023, 14:46', img: 'https://cet.vnu.edu.vn/assets/images/TTKT/no-image.png', short: '9h10 ngày 18 tháng Ba năm 2023, Trung tâm Khảo thí Đại học Quốc gia Hà Nội mở cổng thông tin tiếp nhận thí sinh đăng ký tham dự kỳ thi Đánh giá năng lực học sinh trung học phổ thông (HSA) bốn đợt thi (305, 306, 307 và 308) tổ chức trong tháng 5-6/2023. Quy mô dự kiến phục vụ các đợt thi này khoảng 62.500 máy thi. Thời điểm thí sinh đăng truy cập cao điểm, cổng thông tin ghi nhận phục vụ gần 60.000 thí sinh đăng ký lúc 9h30 cùng ngày.' },
    {id: '7',tag: 'chung',title: 'Hòa Lạc thêm xanh', date: '15/02/2023, 17:14', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/38ad5879-a1d3-47e2-a816-78a93c5dc9b5/download', short: 'Hưởng ứng phong trào Tết trồng cây năm 2023 do Đại học Quốc gia Hà Nội (ĐHQGHN) phát động, Trung tâm Khảo thí ĐHQGHN cùng Trung tâm Kiểm định chất lượng giáo dục - ĐHQGHN và Viện Đảm bảo chất lượng giáo dục đã tổ chức “Tết trồng cây năm 2023 - Cho Hòa Lạc thêm xanh”. Đây là hoạt động cộng đồng nhận được sự hưởng ứng tích cực của toàn thể cán bộ Trung tâm Khảo thí ĐHQGHN.' },
    {id: '8',tag: 'chung',title: 'Bản tin về đăng ký thi Đánh giá năng lực các đợt tháng 3 và 4 năm 2023', date: '06/02/2023, 18:14', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/187311d7-0a26-47a5-849d-5a811e8a8066/download', short: 'Năm 2023, Trung tâm Khảo thí ĐHQGHN được giao nhiệm vụ tổ chức 8 đợt thi Đánh giá năng lực học sinh trung học phổ thông (HSA) từ tháng 3 đến tháng 6. Sáng 9h00 ngày 6.2.2023, hệ thống đăng ký thi HSA mở phục vụ 45.000 chỗ cho thí sinh đăng ký dự thi....' },
    {id: '9',tag: 'dai hoc',title: 'Trung tâm Khảo thí Đại học Quốc gia Hà Nội ký thỏa thuận hợp tác với Trường Đại học Việt Nhật Đại học Quốc gia Hà Nội', date: '17/01/2023, 17:27', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/f9fa5903-d63c-4808-9306-3be4c93b56dd/download', short: 'Chiều ngày 16/01/2023, Trung tâm Khảo thí Đại học Quốc gia Hà Nội (ĐHQGHN) đã ký kết biên bản ghi nhớ hợp tác với Trường Đại học Việt Nhật ĐHQGHN.' },
    {id: '10',tag: 'sau dai hoc',title: 'Hướng tới phục vụ 70.000 thí sinh dự thi HSA năm 2023', date: '01/01/2023, 21:55', img: 'https://cet.vnu.edu.vn/gw/imageresize/unsafe/267x181/smart/cet.vnu.edu.vn/gw/file/v5/FileObject/public/2fe17d54-4ee8-4bad-aef2-d139244b9233/download', short: 'Mùa tuyển sinh năm 2023 đã chính thức khởi động và kỳ thi Đánh giá năng lực luôn thu hút được sự quan tâm lớn của xã hội. Nhằm cung cấp thông tin về kỳ thi này, chúng tôi phỏng vấn với GS. TS Nguyễn Tiến Thảo – Giám đốc Trung tâm Khảo thí về kỳ thi HSA năm tới.' },
  ]
}
